# # [START runtime]
# runtime: nodejs12
# instance_class: F1
# # [END runtime]

# # [START handlers]
# service: teachers
# handlers:
#   - url: /
#     static_files: build/index.html
#     upload: build/index.html

#   - url: /(.*)
#     static_files: build/\1
#     upload: build/(.*)
# # [END handlers]

env: standard
runtime: nodejs12
service: "rs-sd"
instance_class: F1

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html
    secure: always
